name = "cfduty"
main = "src/worker.js"
compatibility_date = "2025-04-09"

workers_dev = false

[observability]
enabled = true

[[workflows]]
name = "cfduty-workflow"
binding = "WORKFLOW"
class_name = "AlertWorkflow"

[env.dev]
name = "cfduty-dev"
compatibility_date = "2025-04-09"

[[env.dev.workflows]]
name = "cfduty-workflow-dev"
binding = "WORKFLOW"
class_name = "AlertWorkflow"
